run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - goconst
    - gocritic
    - gocyclo
    - goimports
    - gofmt
    - gosimple
    - govet
    - staticcheck
linters-settings:
  staticcheck:
    checks:
      - all
      - '-SA1019' # disable the rule SA1000
  gocritic:
    disabled-checks:
      - yodaStyleExpr
    enabled-tags:
      - diagnostic
      - style
      - performance
      - opinionated
    settings:
      hugeParam:
        sizeThreshold: 384
      rangeValCopy:
        sizeThreshold: 384
  gofmt:
    simplify: true
