name: Stub tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    name: Go ubuntu-latest 1.18.x - Stub tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
        with:
          go-version: 1.18.x

      - name: Run tests on stubs
        shell: bash
        env:
          GOARCH: amd64
        run: |
          ./bin/test-stubs-fail test-stubs
